name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: install pnpm
        uses: pnpm/action-setup@v2

      - name: set node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: install dependencies
        run: pnpm install

      - name: generate changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: build
        run: pnpm run build

      - name: publish
        run: cd dist && npx vsce publish -p ${{secrets.VSCE_TOKEN}} --no-dependencies
        env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
